[package]
name = "ayaka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
ayaka-core = { path = "../ayaka-core" }
ayaka-error = { path = "../ayaka-error" }
ayaka-executor = { path = "../ayaka-executor" }
ayaka-request = { path = "../ayaka-request" }
ayaka-scheduler = { path = "../ayaka-scheduler" }
ayaka-server = { path = "../ayaka-server" }
ayaka-telemetry = { path = "../ayaka-telemetry" }
