#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  AYAKA_STATUS_OK = 0,
  AYAKA_STATUS_INVALID_ARGUMENT = 1,
  AYAKA_STATUS_DTYPE_ERROR = 2,
  AYAKA_STATUS_SHAPE_ERROR = 3,
  AYAKA_STATUS_DEVICE_ERROR = 4,
  AYAKA_STATUS_UNSUPPORTED = 5,
  AYAKA_STATUS_OUT_OF_MEMORY = 6,
  AYAKA_STATUS_CONTEXT_LENGTH_EXCEEDED = 7,
  AYAKA_STATUS_NOT_FOUND = 8,
  AYAKA_STATUS_ABI_MISMATCH = 9,
  AYAKA_STATUS_KERNEL_LAUNCH_ERROR = 10,
  AYAKA_STATUS_STREAM_ERROR = 11,
  AYAKA_STATUS_INTERNAL_ERROR = 12,
  AYAKA_STATUS_CANCELLED = 13,
} ayaka_status_code_t;

#ifdef __cplusplus
}
#endif
