[package]
name = "ayaka-hub"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hf-hub.workspace = true
reqwest = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "fs"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
dirs.workspace = true
ayaka-utils = { workspace = true }
fd-lock = "4.0"
indicatif.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
tempfile.workspace = true
tracing-test = "0.2.0"
tokio-test = "0.4"
tracing-subscriber.workspace = true
futures.workspace = true
safetensors.workspace = true
memmap2.workspace = true
tokenizers.workspace = true
serial_test = "3"
ayaka-tokenizer = { path = "../ayaka-tokenizer" }
