[package]
name = "ayaka-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
bitflags = { version = "2.11.1", features = ["serde"] }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
