[package]
name = "ayaka-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
serde.workspace = true
thiserror.workspace = true
tokenizers.workspace = true

[dev-dependencies]
serde_json.workspace = true
