[package]
name = "ayaka-tokenizer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["all-backends", "hub-download"]
all-backends = ["backend-hf", "backend-spm", "backend-tiktoken", "backend-tekken"]
backend-hf = ["dep:tokenizers"]
backend-spm = ["dep:sentencepiece"]
backend-tiktoken = ["dep:tiktoken-rs", "dep:rustc-hash"]
backend-tekken = []
hub-download = ["dep:hf-hub", "dep:tokio"]

[dependencies]
base64.workspace = true
dirs.workspace = true
hf-hub = { workspace = true, optional = true }
minijinja.workspace = true
rayon.workspace = true
sentencepiece = { version = "0.13.1", optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tiktoken-rs = { version = "0.11.0", optional = true }
tokenizers = { workspace = true, optional = true }
tokio = { workspace = true, features = ["fs", "rt"], optional = true }
rustc-hash = { version = "1.1.0", optional = true }

[dev-dependencies]
tempfile.workspace = true
