[package]
name = "ayaka-sampling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
candle-core = "0.10.2"
candle-nn = "0.10.2"
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
