[package]
name = "ayaka-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []
cuda = ["dep:ayaka-kernel-api", "ayaka-kernel-api/cuda"]

[dependencies]
ayaka-core = { path = "../ayaka-core" }
ayaka-error = { path = "../ayaka-error" }
ayaka-kernel-api = { path = "../ayaka-kernel-api", optional = true }
tracing.workspace = true
