[package]
name = "ayaka-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
cuda = ["candle-core/cuda"]
metal = ["candle-core/metal"]

[dependencies]
ayaka-core = { version = "0.1.0", path = "../ayaka-core" }
candle-core.workspace = true
crossbeam.workspace = true
indicatif.workspace = true
libc.workspace = true
opentelemetry.workspace = true
rayon.workspace = true
sysinfo.workspace = true
tqdm.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
